name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "${{ matrix.os }}-${{ matrix.mpi }}-${{ matrix.build }}"
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-slim
            mpi: openmpi
            mpi-version: "5.0"
            build: Release

    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.12
          auto-update-conda: false
          channels: andrsd,defaults

      - name: Checkout source
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          conda install \
            cmake \
            make \
            ${{ matrix.mpi }}-mpicc=${{ matrix.mpi-version }} \
            ${{ matrix.mpi }}-mpicxx=${{ matrix.mpi-version }} \
            gtest \
            lcov
